services:
  postgres:
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty123
      # default user : postgres
      # - POSTGRES_USER=pguser1
      # - POSTGRES_DB=db_commerce
